version: 1.0.0-beta7-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
clone_depth: 1services: mongodb
init:
  - git config --global core.autocrlf true
build_script:
  - build.cmd
build:
  verbosity: minimal