# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.
#   - Doc: http://www.appveyor.com/docs/appveyor-yml

#---------------------------------#
#      general configuration      #
#---------------------------------#

version: 1.0.0-beta8-{build}
pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master


#---------------------------------#
#    environment configuration    #
#---------------------------------#


# Operating system (build VM template)
os: Windows Server 2012


# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# set clone depth
clone_depth: 5                      # clone entire repository history if not defined

# enable service required for build/tests
services: 
  - mongodb


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script:
  - build.cmd


# build Configuration, i.e. Debug, Release, etc.
# Test config does not build the sample site
configuration:
  - Test


#---------------------------------#
#       tests configuration       #
#---------------------------------#

# this turns of AppVeyor automatic searching for test-assemblies, not the actual testing
test: off


#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy: off