version: 1.0.0-beta8-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
clone_depth: 1

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf true

# this turns of AppVeyor automatic searching for test-assemblies, not the actual testing
test: off
deploy: off

services: mongodb

build_script:
  - build.cmd

#environment:
#  XUNIT_TEST_VISITOR: Xunit.KRunner.AppVeyor

