version: 1.0.0-beta7-{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
clone_depth: 1services: mongodb
before_build:
- powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
- dnvm install 1.0.0-beta7
- dnvm use 1.0.0-beta7
- dnvm list
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
build:
  verbosity: minimal